2018/01/16 22:03:37 [alert] 2395#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/16 22:03:37 [notice] 2395#0: signal process started
2018/01/16 23:25:55 [alert] 3284#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/16 23:55:01 [alert] 3592#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/16 23:55:01 [notice] 3592#0: signal process started
2018/01/16 23:55:04 [alert] 3601#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:03:07 [alert] 3735#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:03:07 [notice] 3735#0: signal process started
2018/01/17 00:03:07 [alert] 3602#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:10:10 [alert] 3867#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:10:10 [notice] 3867#0: signal process started
2018/01/17 00:10:10 [alert] 3602#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:10:15 [error] 3870#0: *8 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:19 [error] 3870#0: *8 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:19 [error] 3870#0: *8 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:19 [error] 3870#0: *8 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:33 [alert] 3891#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:10:33 [notice] 3891#0: signal process started
2018/01/17 00:10:33 [alert] 3900#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:10:33 [notice] 3900#0: signal process started
2018/01/17 00:10:33 [error] 3900#0: open() "/usr/local/openresty/nginx/logs/nginx.pid" failed (2: No such file or directory)
2018/01/17 00:10:37 [alert] 3917#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:10:38 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:39 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:39 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:39 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:39 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:10:55 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:23 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:24 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:24 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:24 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:24 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:24 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:24 [error] 3919#0: *1 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:27 [alert] 3951#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:11:27 [notice] 3951#0: signal process started
2018/01/17 00:11:27 [alert] 3918#0: lua_code_cache is off; this will hurt performance in /usr/local/openresty/nginx/conf/lua.conf:9
2018/01/17 00:11:28 [error] 3919#0: *4 failed to load external Lua file "/usr/example/lua/test_other.lua": cannot open /usr/example/lua/test_other.lua: No such file or directory, client: 127.0.0.1, server: _, request: "GET /lua_other HTTP/1.1", host: "localhost:8080"
2018/01/17 00:11:42 [error] 3954#0: *7 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_request.lua:15: attempt to perform arithmetic on field 'user' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/nginx/lua/test_request.lua: in function </usr/local/openresty/nginx/lua/test_request.lua:1>, client: 127.0.0.1, server: _, request: "POST /lua_request/1/2?a=3 HTTP/1.1", host: "127.0.0.1:8080"
2018/01/17 00:11:58 [error] 3954#0: *8 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_request.lua:15: attempt to perform arithmetic on field 'user' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/openresty/nginx/lua/test_request.lua: in function </usr/local/openresty/nginx/lua/test_request.lua:1>, client: 127.0.0.1, server: _, request: "POST /lua_request/1/2?a=3&b=4 HTTP/1.1", host: "127.0.0.1:8080"
2018/01/17 00:17:46 [notice] 4142#0: signal process started
2018/01/17 00:17:49 [error] 4145#0: *9 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:17:49 [error] 4145#0: *10 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:17:51 [error] 4145#0: *11 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:17:55 [notice] 4153#0: signal process started
2018/01/17 00:17:57 [notice] 4162#0: signal process started
2018/01/17 00:17:57 [error] 4162#0: open() "/usr/local/openresty/nginx/logs/nginx.pid" failed (2: No such file or directory)
2018/01/17 00:18:01 [error] 4173#0: *1 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:01 [error] 4173#0: *2 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:02 [error] 4173#0: *3 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:02 [error] 4173#0: *4 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:02 [error] 4173#0: *5 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:02 [error] 4173#0: *6 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:03 [error] 4173#0: *7 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:04 [error] 4173#0: *8 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:06 [error] 4173#0: *9 lua entry thread aborted: runtime error: /usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: expecting 3 or 4 arguments, but only seen 2
stack traceback:
coroutine 0:
	[C]: in function 'incr'
	/usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:14: in function </usr/local/openresty/nginx/lua/test_lua_shared_dict.lua:1>, client: 127.0.0.1, server: _, request: "GET /lua_shared_dict HTTP/1.1", host: "localhost:8080"
2018/01/17 00:18:56 [notice] 4219#0: signal process started
